version: '3'

services:
  nuxt:
    build: ./app/
    container_name: crisisite-website
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx:
    image: nginx:1.17
    container_name: crisisite-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_RPWD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USR
      MYSQL_PASSWORD: $MYSQL_PWD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wp-content/plugins/czk-form:/var/www/html/wp-content/plugins/czk-form
      - ./wp-content/plugins/czk-map:/var/www/html/wp-content/plugins/czk-map
      - ./wp-content/plugins/czk-settings:/var/www/html/wp-content/plugins/czk-settings
      - ./wp-content/themes/czk:/var/www/html/wp-content/themes/czk
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_RPWD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USR
      MYSQL_PASSWORD: $MYSQL_PWD
volumes:
    db_data: {}